# CMake generated Testfile for 
# Source directory: /home/z/catkin_google_ws/src/cartographer_ros/cartographer_ros
# Build directory: /home/z/catkin_google_ws/build_isolated/cartographer_ros
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_cartographer_ros_gtest_configuration_files_test "/home/z/catkin_google_ws/build_isolated/cartographer_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/z/catkin_google_ws/build_isolated/cartographer_ros/test_results/cartographer_ros/gtest-configuration_files_test.xml" "--return-code" "/home/z/catkin_google_ws/devel_isolated/cartographer_ros/lib/cartographer_ros/configuration_files_test --gtest_output=xml:/home/z/catkin_google_ws/build_isolated/cartographer_ros/test_results/cartographer_ros/gtest-configuration_files_test.xml")
set_tests_properties(_ctest_cartographer_ros_gtest_configuration_files_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/z/catkin_google_ws/src/cartographer_ros/cartographer_ros/CMakeLists.txt;145;catkin_add_gtest;/home/z/catkin_google_ws/src/cartographer_ros/cartographer_ros/CMakeLists.txt;0;")
add_test(_ctest_cartographer_ros_gtest_msg_conversion_test "/home/z/catkin_google_ws/build_isolated/cartographer_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/z/catkin_google_ws/build_isolated/cartographer_ros/test_results/cartographer_ros/gtest-msg_conversion_test.xml" "--return-code" "/home/z/catkin_google_ws/devel_isolated/cartographer_ros/lib/cartographer_ros/msg_conversion_test --gtest_output=xml:/home/z/catkin_google_ws/build_isolated/cartographer_ros/test_results/cartographer_ros/gtest-msg_conversion_test.xml")
set_tests_properties(_ctest_cartographer_ros_gtest_msg_conversion_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/z/catkin_google_ws/src/cartographer_ros/cartographer_ros/CMakeLists.txt;145;catkin_add_gtest;/home/z/catkin_google_ws/src/cartographer_ros/cartographer_ros/CMakeLists.txt;0;")
add_test(_ctest_cartographer_ros_gtest_time_conversion_test "/home/z/catkin_google_ws/build_isolated/cartographer_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/z/catkin_google_ws/build_isolated/cartographer_ros/test_results/cartographer_ros/gtest-time_conversion_test.xml" "--return-code" "/home/z/catkin_google_ws/devel_isolated/cartographer_ros/lib/cartographer_ros/time_conversion_test --gtest_output=xml:/home/z/catkin_google_ws/build_isolated/cartographer_ros/test_results/cartographer_ros/gtest-time_conversion_test.xml")
set_tests_properties(_ctest_cartographer_ros_gtest_time_conversion_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/z/catkin_google_ws/src/cartographer_ros/cartographer_ros/CMakeLists.txt;145;catkin_add_gtest;/home/z/catkin_google_ws/src/cartographer_ros/cartographer_ros/CMakeLists.txt;0;")
subdirs("gtest")
subdirs("cartographer_ros")
