// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_2d.proto

#ifndef PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f2d_2eproto
#define PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f2d_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f2d_2eproto 

namespace protobuf_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f2d_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f2d_2eproto
namespace cartographer {
namespace mapping {
namespace scan_matching {
namespace proto {
class FastCorrelativeScanMatcherOptions2D;
class FastCorrelativeScanMatcherOptions2DDefaultTypeInternal;
extern FastCorrelativeScanMatcherOptions2DDefaultTypeInternal _FastCorrelativeScanMatcherOptions2D_default_instance_;
}  // namespace proto
}  // namespace scan_matching
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> ::cartographer::mapping::scan_matching::proto::FastCorrelativeScanMatcherOptions2D* Arena::CreateMaybeMessage<::cartographer::mapping::scan_matching::proto::FastCorrelativeScanMatcherOptions2D>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cartographer {
namespace mapping {
namespace scan_matching {
namespace proto {

// ===================================================================

class FastCorrelativeScanMatcherOptions2D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D) */ {
 public:
  FastCorrelativeScanMatcherOptions2D();
  virtual ~FastCorrelativeScanMatcherOptions2D();

  FastCorrelativeScanMatcherOptions2D(const FastCorrelativeScanMatcherOptions2D& from);

  inline FastCorrelativeScanMatcherOptions2D& operator=(const FastCorrelativeScanMatcherOptions2D& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FastCorrelativeScanMatcherOptions2D(FastCorrelativeScanMatcherOptions2D&& from) noexcept
    : FastCorrelativeScanMatcherOptions2D() {
    *this = ::std::move(from);
  }

  inline FastCorrelativeScanMatcherOptions2D& operator=(FastCorrelativeScanMatcherOptions2D&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FastCorrelativeScanMatcherOptions2D& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FastCorrelativeScanMatcherOptions2D* internal_default_instance() {
    return reinterpret_cast<const FastCorrelativeScanMatcherOptions2D*>(
               &_FastCorrelativeScanMatcherOptions2D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FastCorrelativeScanMatcherOptions2D* other);
  friend void swap(FastCorrelativeScanMatcherOptions2D& a, FastCorrelativeScanMatcherOptions2D& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FastCorrelativeScanMatcherOptions2D* New() const final {
    return CreateMaybeMessage<FastCorrelativeScanMatcherOptions2D>(NULL);
  }

  FastCorrelativeScanMatcherOptions2D* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FastCorrelativeScanMatcherOptions2D>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FastCorrelativeScanMatcherOptions2D& from);
  void MergeFrom(const FastCorrelativeScanMatcherOptions2D& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FastCorrelativeScanMatcherOptions2D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double linear_search_window = 3;
  void clear_linear_search_window();
  static const int kLinearSearchWindowFieldNumber = 3;
  double linear_search_window() const;
  void set_linear_search_window(double value);

  // double angular_search_window = 4;
  void clear_angular_search_window();
  static const int kAngularSearchWindowFieldNumber = 4;
  double angular_search_window() const;
  void set_angular_search_window(double value);

  // int32 branch_and_bound_depth = 2;
  void clear_branch_and_bound_depth();
  static const int kBranchAndBoundDepthFieldNumber = 2;
  ::google::protobuf::int32 branch_and_bound_depth() const;
  void set_branch_and_bound_depth(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double linear_search_window_;
  double angular_search_window_;
  ::google::protobuf::int32 branch_and_bound_depth_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f2d_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FastCorrelativeScanMatcherOptions2D

// double linear_search_window = 3;
inline void FastCorrelativeScanMatcherOptions2D::clear_linear_search_window() {
  linear_search_window_ = 0;
}
inline double FastCorrelativeScanMatcherOptions2D::linear_search_window() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.linear_search_window)
  return linear_search_window_;
}
inline void FastCorrelativeScanMatcherOptions2D::set_linear_search_window(double value) {
  
  linear_search_window_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.linear_search_window)
}

// double angular_search_window = 4;
inline void FastCorrelativeScanMatcherOptions2D::clear_angular_search_window() {
  angular_search_window_ = 0;
}
inline double FastCorrelativeScanMatcherOptions2D::angular_search_window() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.angular_search_window)
  return angular_search_window_;
}
inline void FastCorrelativeScanMatcherOptions2D::set_angular_search_window(double value) {
  
  angular_search_window_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.angular_search_window)
}

// int32 branch_and_bound_depth = 2;
inline void FastCorrelativeScanMatcherOptions2D::clear_branch_and_bound_depth() {
  branch_and_bound_depth_ = 0;
}
inline ::google::protobuf::int32 FastCorrelativeScanMatcherOptions2D::branch_and_bound_depth() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.branch_and_bound_depth)
  return branch_and_bound_depth_;
}
inline void FastCorrelativeScanMatcherOptions2D::set_branch_and_bound_depth(::google::protobuf::int32 value) {
  
  branch_and_bound_depth_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.branch_and_bound_depth)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace scan_matching
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f2d_2eproto
