// Generated by gencpp from file tracer_msgs/TracerLightState.msg
// DO NOT EDIT!


#ifndef TRACER_MSGS_MESSAGE_TRACERLIGHTSTATE_H
#define TRACER_MSGS_MESSAGE_TRACERLIGHTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tracer_msgs
{
template <class ContainerAllocator>
struct TracerLightState_
{
  typedef TracerLightState_<ContainerAllocator> Type;

  TracerLightState_()
    : mode(0)
    , custom_value(0)  {
    }
  TracerLightState_(const ContainerAllocator& _alloc)
    : mode(0)
    , custom_value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _custom_value_type;
  _custom_value_type custom_value;





  typedef boost::shared_ptr< ::tracer_msgs::TracerLightState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracer_msgs::TracerLightState_<ContainerAllocator> const> ConstPtr;

}; // struct TracerLightState_

typedef ::tracer_msgs::TracerLightState_<std::allocator<void> > TracerLightState;

typedef boost::shared_ptr< ::tracer_msgs::TracerLightState > TracerLightStatePtr;
typedef boost::shared_ptr< ::tracer_msgs::TracerLightState const> TracerLightStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracer_msgs::TracerLightState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracer_msgs::TracerLightState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tracer_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tracer_msgs': ['/home/z/catkin_ws/src/tracer_ros/tracer_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracer_msgs::TracerLightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracer_msgs::TracerLightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracer_msgs::TracerLightState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51866248399dda20e62f6b250914288e";
  }

  static const char* value(const ::tracer_msgs::TracerLightState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51866248399dda20ULL;
  static const uint64_t static_value2 = 0xe62f6b250914288eULL;
};

template<class ContainerAllocator>
struct DataType< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracer_msgs/TracerLightState";
  }

  static const char* value(const ::tracer_msgs::TracerLightState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n\
uint8 custom_value\n\
";
  }

  static const char* value(const ::tracer_msgs::TracerLightState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.custom_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TracerLightState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracer_msgs::TracerLightState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracer_msgs::TracerLightState_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "custom_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.custom_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACER_MSGS_MESSAGE_TRACERLIGHTSTATE_H
