// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/2d/cell_limits.proto

#ifndef PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto
#define PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto 

namespace protobuf_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto
namespace cartographer {
namespace mapping {
namespace proto {
class CellLimits;
class CellLimitsDefaultTypeInternal;
extern CellLimitsDefaultTypeInternal _CellLimits_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> ::cartographer::mapping::proto::CellLimits* Arena::CreateMaybeMessage<::cartographer::mapping::proto::CellLimits>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

class CellLimits : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.CellLimits) */ {
 public:
  CellLimits();
  virtual ~CellLimits();

  CellLimits(const CellLimits& from);

  inline CellLimits& operator=(const CellLimits& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CellLimits(CellLimits&& from) noexcept
    : CellLimits() {
    *this = ::std::move(from);
  }

  inline CellLimits& operator=(CellLimits&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CellLimits& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CellLimits* internal_default_instance() {
    return reinterpret_cast<const CellLimits*>(
               &_CellLimits_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CellLimits* other);
  friend void swap(CellLimits& a, CellLimits& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CellLimits* New() const final {
    return CreateMaybeMessage<CellLimits>(NULL);
  }

  CellLimits* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CellLimits>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CellLimits& from);
  void MergeFrom(const CellLimits& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CellLimits* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 num_x_cells = 1;
  void clear_num_x_cells();
  static const int kNumXCellsFieldNumber = 1;
  ::google::protobuf::int32 num_x_cells() const;
  void set_num_x_cells(::google::protobuf::int32 value);

  // int32 num_y_cells = 2;
  void clear_num_y_cells();
  static const int kNumYCellsFieldNumber = 2;
  ::google::protobuf::int32 num_y_cells() const;
  void set_num_y_cells(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.CellLimits)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 num_x_cells_;
  ::google::protobuf::int32 num_y_cells_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CellLimits

// int32 num_x_cells = 1;
inline void CellLimits::clear_num_x_cells() {
  num_x_cells_ = 0;
}
inline ::google::protobuf::int32 CellLimits::num_x_cells() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.CellLimits.num_x_cells)
  return num_x_cells_;
}
inline void CellLimits::set_num_x_cells(::google::protobuf::int32 value) {
  
  num_x_cells_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.CellLimits.num_x_cells)
}

// int32 num_y_cells = 2;
inline void CellLimits::clear_num_y_cells() {
  num_y_cells_ = 0;
}
inline ::google::protobuf::int32 CellLimits::num_y_cells() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.CellLimits.num_y_cells)
  return num_y_cells_;
}
inline void CellLimits::set_num_y_cells(::google::protobuf::int32 value) {
  
  num_y_cells_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.CellLimits.num_y_cells)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto
