// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/2d/probability_grid.proto

#ifndef PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2f2d_2fprobability_5fgrid_2eproto
#define PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2f2d_2fprobability_5fgrid_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cartographer_2fmapping_2fproto_2f2d_2fprobability_5fgrid_2eproto 

namespace protobuf_cartographer_2fmapping_2fproto_2f2d_2fprobability_5fgrid_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2f2d_2fprobability_5fgrid_2eproto
namespace cartographer {
namespace mapping {
namespace proto {
class ProbabilityGrid;
class ProbabilityGridDefaultTypeInternal;
extern ProbabilityGridDefaultTypeInternal _ProbabilityGrid_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> ::cartographer::mapping::proto::ProbabilityGrid* Arena::CreateMaybeMessage<::cartographer::mapping::proto::ProbabilityGrid>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

class ProbabilityGrid : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.ProbabilityGrid) */ {
 public:
  ProbabilityGrid();
  virtual ~ProbabilityGrid();

  ProbabilityGrid(const ProbabilityGrid& from);

  inline ProbabilityGrid& operator=(const ProbabilityGrid& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProbabilityGrid(ProbabilityGrid&& from) noexcept
    : ProbabilityGrid() {
    *this = ::std::move(from);
  }

  inline ProbabilityGrid& operator=(ProbabilityGrid&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProbabilityGrid& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProbabilityGrid* internal_default_instance() {
    return reinterpret_cast<const ProbabilityGrid*>(
               &_ProbabilityGrid_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ProbabilityGrid* other);
  friend void swap(ProbabilityGrid& a, ProbabilityGrid& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProbabilityGrid* New() const final {
    return CreateMaybeMessage<ProbabilityGrid>(NULL);
  }

  ProbabilityGrid* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProbabilityGrid>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProbabilityGrid& from);
  void MergeFrom(const ProbabilityGrid& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProbabilityGrid* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ProbabilityGrid)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2fmapping_2fproto_2f2d_2fprobability_5fgrid_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProbabilityGrid

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2f2d_2fprobability_5fgrid_2eproto
