; Auto-generated. Do not edit!


(cl:in-package turtlebot_actions-msg)


;//! \htmlinclude FindFiducialFeedback.msg.html

(cl:defclass <FindFiducialFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FindFiducialFeedback (<FindFiducialFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindFiducialFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindFiducialFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_actions-msg:<FindFiducialFeedback> is deprecated: use turtlebot_actions-msg:FindFiducialFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindFiducialFeedback>) ostream)
  "Serializes a message object of type '<FindFiducialFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindFiducialFeedback>) istream)
  "Deserializes a message object of type '<FindFiducialFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindFiducialFeedback>)))
  "Returns string type for a message object of type '<FindFiducialFeedback>"
  "turtlebot_actions/FindFiducialFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindFiducialFeedback)))
  "Returns string type for a message object of type 'FindFiducialFeedback"
  "turtlebot_actions/FindFiducialFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindFiducialFeedback>)))
  "Returns md5sum for a message object of type '<FindFiducialFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindFiducialFeedback)))
  "Returns md5sum for a message object of type 'FindFiducialFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindFiducialFeedback>)))
  "Returns full string definition for message of type '<FindFiducialFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindFiducialFeedback)))
  "Returns full string definition for message of type 'FindFiducialFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindFiducialFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindFiducialFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FindFiducialFeedback
))
