// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/submap.proto

#ifndef PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fsubmap_2eproto
#define PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fsubmap_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/mapping/proto/2d/grid_2d.pb.h"
#include "cartographer/mapping/proto/3d/hybrid_grid.pb.h"
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto 

namespace protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto
namespace cartographer {
namespace mapping {
namespace proto {
class Submap2D;
class Submap2DDefaultTypeInternal;
extern Submap2DDefaultTypeInternal _Submap2D_default_instance_;
class Submap3D;
class Submap3DDefaultTypeInternal;
extern Submap3DDefaultTypeInternal _Submap3D_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> ::cartographer::mapping::proto::Submap2D* Arena::CreateMaybeMessage<::cartographer::mapping::proto::Submap2D>(Arena*);
template<> ::cartographer::mapping::proto::Submap3D* Arena::CreateMaybeMessage<::cartographer::mapping::proto::Submap3D>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

class Submap2D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.Submap2D) */ {
 public:
  Submap2D();
  virtual ~Submap2D();

  Submap2D(const Submap2D& from);

  inline Submap2D& operator=(const Submap2D& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Submap2D(Submap2D&& from) noexcept
    : Submap2D() {
    *this = ::std::move(from);
  }

  inline Submap2D& operator=(Submap2D&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Submap2D& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Submap2D* internal_default_instance() {
    return reinterpret_cast<const Submap2D*>(
               &_Submap2D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Submap2D* other);
  friend void swap(Submap2D& a, Submap2D& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Submap2D* New() const final {
    return CreateMaybeMessage<Submap2D>(NULL);
  }

  Submap2D* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Submap2D>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Submap2D& from);
  void MergeFrom(const Submap2D& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Submap2D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  bool has_local_pose() const;
  void clear_local_pose();
  static const int kLocalPoseFieldNumber = 1;
  private:
  const ::cartographer::transform::proto::Rigid3d& _internal_local_pose() const;
  public:
  const ::cartographer::transform::proto::Rigid3d& local_pose() const;
  ::cartographer::transform::proto::Rigid3d* release_local_pose();
  ::cartographer::transform::proto::Rigid3d* mutable_local_pose();
  void set_allocated_local_pose(::cartographer::transform::proto::Rigid3d* local_pose);

  // .cartographer.mapping.proto.Grid2D grid = 4;
  bool has_grid() const;
  void clear_grid();
  static const int kGridFieldNumber = 4;
  private:
  const ::cartographer::mapping::proto::Grid2D& _internal_grid() const;
  public:
  const ::cartographer::mapping::proto::Grid2D& grid() const;
  ::cartographer::mapping::proto::Grid2D* release_grid();
  ::cartographer::mapping::proto::Grid2D* mutable_grid();
  void set_allocated_grid(::cartographer::mapping::proto::Grid2D* grid);

  // int32 num_range_data = 2;
  void clear_num_range_data();
  static const int kNumRangeDataFieldNumber = 2;
  ::google::protobuf::int32 num_range_data() const;
  void set_num_range_data(::google::protobuf::int32 value);

  // bool finished = 3;
  void clear_finished();
  static const int kFinishedFieldNumber = 3;
  bool finished() const;
  void set_finished(bool value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.Submap2D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Rigid3d* local_pose_;
  ::cartographer::mapping::proto::Grid2D* grid_;
  ::google::protobuf::int32 num_range_data_;
  bool finished_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Submap3D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.Submap3D) */ {
 public:
  Submap3D();
  virtual ~Submap3D();

  Submap3D(const Submap3D& from);

  inline Submap3D& operator=(const Submap3D& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Submap3D(Submap3D&& from) noexcept
    : Submap3D() {
    *this = ::std::move(from);
  }

  inline Submap3D& operator=(Submap3D&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Submap3D& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Submap3D* internal_default_instance() {
    return reinterpret_cast<const Submap3D*>(
               &_Submap3D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Submap3D* other);
  friend void swap(Submap3D& a, Submap3D& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Submap3D* New() const final {
    return CreateMaybeMessage<Submap3D>(NULL);
  }

  Submap3D* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Submap3D>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Submap3D& from);
  void MergeFrom(const Submap3D& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Submap3D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Rigid3d local_pose = 1;
  bool has_local_pose() const;
  void clear_local_pose();
  static const int kLocalPoseFieldNumber = 1;
  private:
  const ::cartographer::transform::proto::Rigid3d& _internal_local_pose() const;
  public:
  const ::cartographer::transform::proto::Rigid3d& local_pose() const;
  ::cartographer::transform::proto::Rigid3d* release_local_pose();
  ::cartographer::transform::proto::Rigid3d* mutable_local_pose();
  void set_allocated_local_pose(::cartographer::transform::proto::Rigid3d* local_pose);

  // .cartographer.mapping.proto.HybridGrid high_resolution_hybrid_grid = 4;
  bool has_high_resolution_hybrid_grid() const;
  void clear_high_resolution_hybrid_grid();
  static const int kHighResolutionHybridGridFieldNumber = 4;
  private:
  const ::cartographer::mapping::proto::HybridGrid& _internal_high_resolution_hybrid_grid() const;
  public:
  const ::cartographer::mapping::proto::HybridGrid& high_resolution_hybrid_grid() const;
  ::cartographer::mapping::proto::HybridGrid* release_high_resolution_hybrid_grid();
  ::cartographer::mapping::proto::HybridGrid* mutable_high_resolution_hybrid_grid();
  void set_allocated_high_resolution_hybrid_grid(::cartographer::mapping::proto::HybridGrid* high_resolution_hybrid_grid);

  // .cartographer.mapping.proto.HybridGrid low_resolution_hybrid_grid = 5;
  bool has_low_resolution_hybrid_grid() const;
  void clear_low_resolution_hybrid_grid();
  static const int kLowResolutionHybridGridFieldNumber = 5;
  private:
  const ::cartographer::mapping::proto::HybridGrid& _internal_low_resolution_hybrid_grid() const;
  public:
  const ::cartographer::mapping::proto::HybridGrid& low_resolution_hybrid_grid() const;
  ::cartographer::mapping::proto::HybridGrid* release_low_resolution_hybrid_grid();
  ::cartographer::mapping::proto::HybridGrid* mutable_low_resolution_hybrid_grid();
  void set_allocated_low_resolution_hybrid_grid(::cartographer::mapping::proto::HybridGrid* low_resolution_hybrid_grid);

  // int32 num_range_data = 2;
  void clear_num_range_data();
  static const int kNumRangeDataFieldNumber = 2;
  ::google::protobuf::int32 num_range_data() const;
  void set_num_range_data(::google::protobuf::int32 value);

  // bool finished = 3;
  void clear_finished();
  static const int kFinishedFieldNumber = 3;
  bool finished() const;
  void set_finished(bool value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.Submap3D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Rigid3d* local_pose_;
  ::cartographer::mapping::proto::HybridGrid* high_resolution_hybrid_grid_;
  ::cartographer::mapping::proto::HybridGrid* low_resolution_hybrid_grid_;
  ::google::protobuf::int32 num_range_data_;
  bool finished_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2fmapping_2fproto_2fsubmap_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Submap2D

// .cartographer.transform.proto.Rigid3d local_pose = 1;
inline bool Submap2D::has_local_pose() const {
  return this != internal_default_instance() && local_pose_ != NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& Submap2D::_internal_local_pose() const {
  return *local_pose_;
}
inline const ::cartographer::transform::proto::Rigid3d& Submap2D::local_pose() const {
  const ::cartographer::transform::proto::Rigid3d* p = local_pose_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.local_pose)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Rigid3d*>(
      &::cartographer::transform::proto::_Rigid3d_default_instance_);
}
inline ::cartographer::transform::proto::Rigid3d* Submap2D::release_local_pose() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap2D.local_pose)
  
  ::cartographer::transform::proto::Rigid3d* temp = local_pose_;
  local_pose_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Rigid3d* Submap2D::mutable_local_pose() {
  
  if (local_pose_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Rigid3d>(GetArenaNoVirtual());
    local_pose_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap2D.local_pose)
  return local_pose_;
}
inline void Submap2D::set_allocated_local_pose(::cartographer::transform::proto::Rigid3d* local_pose) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(local_pose_);
  }
  if (local_pose) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      local_pose = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, local_pose, submessage_arena);
    }
    
  } else {
    
  }
  local_pose_ = local_pose;
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap2D.local_pose)
}

// int32 num_range_data = 2;
inline void Submap2D::clear_num_range_data() {
  num_range_data_ = 0;
}
inline ::google::protobuf::int32 Submap2D::num_range_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.num_range_data)
  return num_range_data_;
}
inline void Submap2D::set_num_range_data(::google::protobuf::int32 value) {
  
  num_range_data_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap2D.num_range_data)
}

// bool finished = 3;
inline void Submap2D::clear_finished() {
  finished_ = false;
}
inline bool Submap2D::finished() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.finished)
  return finished_;
}
inline void Submap2D::set_finished(bool value) {
  
  finished_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap2D.finished)
}

// .cartographer.mapping.proto.Grid2D grid = 4;
inline bool Submap2D::has_grid() const {
  return this != internal_default_instance() && grid_ != NULL;
}
inline const ::cartographer::mapping::proto::Grid2D& Submap2D::_internal_grid() const {
  return *grid_;
}
inline const ::cartographer::mapping::proto::Grid2D& Submap2D::grid() const {
  const ::cartographer::mapping::proto::Grid2D* p = grid_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap2D.grid)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::mapping::proto::Grid2D*>(
      &::cartographer::mapping::proto::_Grid2D_default_instance_);
}
inline ::cartographer::mapping::proto::Grid2D* Submap2D::release_grid() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap2D.grid)
  
  ::cartographer::mapping::proto::Grid2D* temp = grid_;
  grid_ = NULL;
  return temp;
}
inline ::cartographer::mapping::proto::Grid2D* Submap2D::mutable_grid() {
  
  if (grid_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::mapping::proto::Grid2D>(GetArenaNoVirtual());
    grid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap2D.grid)
  return grid_;
}
inline void Submap2D::set_allocated_grid(::cartographer::mapping::proto::Grid2D* grid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(grid_);
  }
  if (grid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      grid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, grid, submessage_arena);
    }
    
  } else {
    
  }
  grid_ = grid;
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap2D.grid)
}

// -------------------------------------------------------------------

// Submap3D

// .cartographer.transform.proto.Rigid3d local_pose = 1;
inline bool Submap3D::has_local_pose() const {
  return this != internal_default_instance() && local_pose_ != NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& Submap3D::_internal_local_pose() const {
  return *local_pose_;
}
inline const ::cartographer::transform::proto::Rigid3d& Submap3D::local_pose() const {
  const ::cartographer::transform::proto::Rigid3d* p = local_pose_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.local_pose)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Rigid3d*>(
      &::cartographer::transform::proto::_Rigid3d_default_instance_);
}
inline ::cartographer::transform::proto::Rigid3d* Submap3D::release_local_pose() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap3D.local_pose)
  
  ::cartographer::transform::proto::Rigid3d* temp = local_pose_;
  local_pose_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Rigid3d* Submap3D::mutable_local_pose() {
  
  if (local_pose_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Rigid3d>(GetArenaNoVirtual());
    local_pose_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap3D.local_pose)
  return local_pose_;
}
inline void Submap3D::set_allocated_local_pose(::cartographer::transform::proto::Rigid3d* local_pose) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(local_pose_);
  }
  if (local_pose) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      local_pose = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, local_pose, submessage_arena);
    }
    
  } else {
    
  }
  local_pose_ = local_pose;
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap3D.local_pose)
}

// int32 num_range_data = 2;
inline void Submap3D::clear_num_range_data() {
  num_range_data_ = 0;
}
inline ::google::protobuf::int32 Submap3D::num_range_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.num_range_data)
  return num_range_data_;
}
inline void Submap3D::set_num_range_data(::google::protobuf::int32 value) {
  
  num_range_data_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap3D.num_range_data)
}

// bool finished = 3;
inline void Submap3D::clear_finished() {
  finished_ = false;
}
inline bool Submap3D::finished() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.finished)
  return finished_;
}
inline void Submap3D::set_finished(bool value) {
  
  finished_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Submap3D.finished)
}

// .cartographer.mapping.proto.HybridGrid high_resolution_hybrid_grid = 4;
inline bool Submap3D::has_high_resolution_hybrid_grid() const {
  return this != internal_default_instance() && high_resolution_hybrid_grid_ != NULL;
}
inline const ::cartographer::mapping::proto::HybridGrid& Submap3D::_internal_high_resolution_hybrid_grid() const {
  return *high_resolution_hybrid_grid_;
}
inline const ::cartographer::mapping::proto::HybridGrid& Submap3D::high_resolution_hybrid_grid() const {
  const ::cartographer::mapping::proto::HybridGrid* p = high_resolution_hybrid_grid_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::mapping::proto::HybridGrid*>(
      &::cartographer::mapping::proto::_HybridGrid_default_instance_);
}
inline ::cartographer::mapping::proto::HybridGrid* Submap3D::release_high_resolution_hybrid_grid() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
  
  ::cartographer::mapping::proto::HybridGrid* temp = high_resolution_hybrid_grid_;
  high_resolution_hybrid_grid_ = NULL;
  return temp;
}
inline ::cartographer::mapping::proto::HybridGrid* Submap3D::mutable_high_resolution_hybrid_grid() {
  
  if (high_resolution_hybrid_grid_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::mapping::proto::HybridGrid>(GetArenaNoVirtual());
    high_resolution_hybrid_grid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
  return high_resolution_hybrid_grid_;
}
inline void Submap3D::set_allocated_high_resolution_hybrid_grid(::cartographer::mapping::proto::HybridGrid* high_resolution_hybrid_grid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(high_resolution_hybrid_grid_);
  }
  if (high_resolution_hybrid_grid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      high_resolution_hybrid_grid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, high_resolution_hybrid_grid, submessage_arena);
    }
    
  } else {
    
  }
  high_resolution_hybrid_grid_ = high_resolution_hybrid_grid;
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap3D.high_resolution_hybrid_grid)
}

// .cartographer.mapping.proto.HybridGrid low_resolution_hybrid_grid = 5;
inline bool Submap3D::has_low_resolution_hybrid_grid() const {
  return this != internal_default_instance() && low_resolution_hybrid_grid_ != NULL;
}
inline const ::cartographer::mapping::proto::HybridGrid& Submap3D::_internal_low_resolution_hybrid_grid() const {
  return *low_resolution_hybrid_grid_;
}
inline const ::cartographer::mapping::proto::HybridGrid& Submap3D::low_resolution_hybrid_grid() const {
  const ::cartographer::mapping::proto::HybridGrid* p = low_resolution_hybrid_grid_;
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::mapping::proto::HybridGrid*>(
      &::cartographer::mapping::proto::_HybridGrid_default_instance_);
}
inline ::cartographer::mapping::proto::HybridGrid* Submap3D::release_low_resolution_hybrid_grid() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
  
  ::cartographer::mapping::proto::HybridGrid* temp = low_resolution_hybrid_grid_;
  low_resolution_hybrid_grid_ = NULL;
  return temp;
}
inline ::cartographer::mapping::proto::HybridGrid* Submap3D::mutable_low_resolution_hybrid_grid() {
  
  if (low_resolution_hybrid_grid_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::mapping::proto::HybridGrid>(GetArenaNoVirtual());
    low_resolution_hybrid_grid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
  return low_resolution_hybrid_grid_;
}
inline void Submap3D::set_allocated_low_resolution_hybrid_grid(::cartographer::mapping::proto::HybridGrid* low_resolution_hybrid_grid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(low_resolution_hybrid_grid_);
  }
  if (low_resolution_hybrid_grid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      low_resolution_hybrid_grid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, low_resolution_hybrid_grid, submessage_arena);
    }
    
  } else {
    
  }
  low_resolution_hybrid_grid_ = low_resolution_hybrid_grid;
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap3D.low_resolution_hybrid_grid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fsubmap_2eproto
