// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/transform/proto/transform.proto

#ifndef PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftransform_2eproto
#define PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftransform_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto 

namespace protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[11];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto
namespace cartographer {
namespace transform {
namespace proto {
class Quaterniond;
class QuaterniondDefaultTypeInternal;
extern QuaterniondDefaultTypeInternal _Quaterniond_default_instance_;
class Quaternionf;
class QuaternionfDefaultTypeInternal;
extern QuaternionfDefaultTypeInternal _Quaternionf_default_instance_;
class Rigid2d;
class Rigid2dDefaultTypeInternal;
extern Rigid2dDefaultTypeInternal _Rigid2d_default_instance_;
class Rigid2f;
class Rigid2fDefaultTypeInternal;
extern Rigid2fDefaultTypeInternal _Rigid2f_default_instance_;
class Rigid3d;
class Rigid3dDefaultTypeInternal;
extern Rigid3dDefaultTypeInternal _Rigid3d_default_instance_;
class Rigid3f;
class Rigid3fDefaultTypeInternal;
extern Rigid3fDefaultTypeInternal _Rigid3f_default_instance_;
class Vector2d;
class Vector2dDefaultTypeInternal;
extern Vector2dDefaultTypeInternal _Vector2d_default_instance_;
class Vector2f;
class Vector2fDefaultTypeInternal;
extern Vector2fDefaultTypeInternal _Vector2f_default_instance_;
class Vector3d;
class Vector3dDefaultTypeInternal;
extern Vector3dDefaultTypeInternal _Vector3d_default_instance_;
class Vector3f;
class Vector3fDefaultTypeInternal;
extern Vector3fDefaultTypeInternal _Vector3f_default_instance_;
class Vector4f;
class Vector4fDefaultTypeInternal;
extern Vector4fDefaultTypeInternal _Vector4f_default_instance_;
}  // namespace proto
}  // namespace transform
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> ::cartographer::transform::proto::Quaterniond* Arena::CreateMaybeMessage<::cartographer::transform::proto::Quaterniond>(Arena*);
template<> ::cartographer::transform::proto::Quaternionf* Arena::CreateMaybeMessage<::cartographer::transform::proto::Quaternionf>(Arena*);
template<> ::cartographer::transform::proto::Rigid2d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid2d>(Arena*);
template<> ::cartographer::transform::proto::Rigid2f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid2f>(Arena*);
template<> ::cartographer::transform::proto::Rigid3d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid3d>(Arena*);
template<> ::cartographer::transform::proto::Rigid3f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid3f>(Arena*);
template<> ::cartographer::transform::proto::Vector2d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector2d>(Arena*);
template<> ::cartographer::transform::proto::Vector2f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector2f>(Arena*);
template<> ::cartographer::transform::proto::Vector3d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector3d>(Arena*);
template<> ::cartographer::transform::proto::Vector3f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector3f>(Arena*);
template<> ::cartographer::transform::proto::Vector4f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector4f>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cartographer {
namespace transform {
namespace proto {

// ===================================================================

class Vector2d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector2d) */ {
 public:
  Vector2d();
  virtual ~Vector2d();

  Vector2d(const Vector2d& from);

  inline Vector2d& operator=(const Vector2d& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Vector2d(Vector2d&& from) noexcept
    : Vector2d() {
    *this = ::std::move(from);
  }

  inline Vector2d& operator=(Vector2d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector2d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector2d* internal_default_instance() {
    return reinterpret_cast<const Vector2d*>(
               &_Vector2d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Vector2d* other);
  friend void swap(Vector2d& a, Vector2d& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Vector2d* New() const final {
    return CreateMaybeMessage<Vector2d>(NULL);
  }

  Vector2d* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Vector2d>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Vector2d& from);
  void MergeFrom(const Vector2d& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector2d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector2d)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector2f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector2f) */ {
 public:
  Vector2f();
  virtual ~Vector2f();

  Vector2f(const Vector2f& from);

  inline Vector2f& operator=(const Vector2f& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Vector2f(Vector2f&& from) noexcept
    : Vector2f() {
    *this = ::std::move(from);
  }

  inline Vector2f& operator=(Vector2f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector2f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector2f* internal_default_instance() {
    return reinterpret_cast<const Vector2f*>(
               &_Vector2f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Vector2f* other);
  friend void swap(Vector2f& a, Vector2f& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Vector2f* New() const final {
    return CreateMaybeMessage<Vector2f>(NULL);
  }

  Vector2f* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Vector2f>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Vector2f& from);
  void MergeFrom(const Vector2f& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector2f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector2f)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector3d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector3d) */ {
 public:
  Vector3d();
  virtual ~Vector3d();

  Vector3d(const Vector3d& from);

  inline Vector3d& operator=(const Vector3d& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Vector3d(Vector3d&& from) noexcept
    : Vector3d() {
    *this = ::std::move(from);
  }

  inline Vector3d& operator=(Vector3d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector3d* internal_default_instance() {
    return reinterpret_cast<const Vector3d*>(
               &_Vector3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Vector3d* other);
  friend void swap(Vector3d& a, Vector3d& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Vector3d* New() const final {
    return CreateMaybeMessage<Vector3d>(NULL);
  }

  Vector3d* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Vector3d>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Vector3d& from);
  void MergeFrom(const Vector3d& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // double z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector3d)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  double z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector3f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector3f) */ {
 public:
  Vector3f();
  virtual ~Vector3f();

  Vector3f(const Vector3f& from);

  inline Vector3f& operator=(const Vector3f& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Vector3f(Vector3f&& from) noexcept
    : Vector3f() {
    *this = ::std::move(from);
  }

  inline Vector3f& operator=(Vector3f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector3f* internal_default_instance() {
    return reinterpret_cast<const Vector3f*>(
               &_Vector3f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Vector3f* other);
  friend void swap(Vector3f& a, Vector3f& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Vector3f* New() const final {
    return CreateMaybeMessage<Vector3f>(NULL);
  }

  Vector3f* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Vector3f>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Vector3f& from);
  void MergeFrom(const Vector3f& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector3f)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector4f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector4f) */ {
 public:
  Vector4f();
  virtual ~Vector4f();

  Vector4f(const Vector4f& from);

  inline Vector4f& operator=(const Vector4f& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Vector4f(Vector4f&& from) noexcept
    : Vector4f() {
    *this = ::std::move(from);
  }

  inline Vector4f& operator=(Vector4f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector4f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector4f* internal_default_instance() {
    return reinterpret_cast<const Vector4f*>(
               &_Vector4f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Vector4f* other);
  friend void swap(Vector4f& a, Vector4f& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Vector4f* New() const final {
    return CreateMaybeMessage<Vector4f>(NULL);
  }

  Vector4f* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Vector4f>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Vector4f& from);
  void MergeFrom(const Vector4f& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector4f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // float t = 4;
  void clear_t();
  static const int kTFieldNumber = 4;
  float t() const;
  void set_t(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector4f)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  float t_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Quaterniond : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Quaterniond) */ {
 public:
  Quaterniond();
  virtual ~Quaterniond();

  Quaterniond(const Quaterniond& from);

  inline Quaterniond& operator=(const Quaterniond& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Quaterniond(Quaterniond&& from) noexcept
    : Quaterniond() {
    *this = ::std::move(from);
  }

  inline Quaterniond& operator=(Quaterniond&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Quaterniond& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Quaterniond* internal_default_instance() {
    return reinterpret_cast<const Quaterniond*>(
               &_Quaterniond_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Quaterniond* other);
  friend void swap(Quaterniond& a, Quaterniond& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Quaterniond* New() const final {
    return CreateMaybeMessage<Quaterniond>(NULL);
  }

  Quaterniond* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Quaterniond>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Quaterniond& from);
  void MergeFrom(const Quaterniond& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quaterniond* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // double y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // double z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // double w = 4;
  void clear_w();
  static const int kWFieldNumber = 4;
  double w() const;
  void set_w(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Quaterniond)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  double z_;
  double w_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Quaternionf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Quaternionf) */ {
 public:
  Quaternionf();
  virtual ~Quaternionf();

  Quaternionf(const Quaternionf& from);

  inline Quaternionf& operator=(const Quaternionf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Quaternionf(Quaternionf&& from) noexcept
    : Quaternionf() {
    *this = ::std::move(from);
  }

  inline Quaternionf& operator=(Quaternionf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Quaternionf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Quaternionf* internal_default_instance() {
    return reinterpret_cast<const Quaternionf*>(
               &_Quaternionf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Quaternionf* other);
  friend void swap(Quaternionf& a, Quaternionf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Quaternionf* New() const final {
    return CreateMaybeMessage<Quaternionf>(NULL);
  }

  Quaternionf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Quaternionf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Quaternionf& from);
  void MergeFrom(const Quaternionf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quaternionf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // float w = 4;
  void clear_w();
  static const int kWFieldNumber = 4;
  float w() const;
  void set_w(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Quaternionf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid2d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid2d) */ {
 public:
  Rigid2d();
  virtual ~Rigid2d();

  Rigid2d(const Rigid2d& from);

  inline Rigid2d& operator=(const Rigid2d& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Rigid2d(Rigid2d&& from) noexcept
    : Rigid2d() {
    *this = ::std::move(from);
  }

  inline Rigid2d& operator=(Rigid2d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid2d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid2d* internal_default_instance() {
    return reinterpret_cast<const Rigid2d*>(
               &_Rigid2d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(Rigid2d* other);
  friend void swap(Rigid2d& a, Rigid2d& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Rigid2d* New() const final {
    return CreateMaybeMessage<Rigid2d>(NULL);
  }

  Rigid2d* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Rigid2d>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Rigid2d& from);
  void MergeFrom(const Rigid2d& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid2d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Vector2d translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  private:
  const ::cartographer::transform::proto::Vector2d& _internal_translation() const;
  public:
  const ::cartographer::transform::proto::Vector2d& translation() const;
  ::cartographer::transform::proto::Vector2d* release_translation();
  ::cartographer::transform::proto::Vector2d* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector2d* translation);

  // double rotation = 2;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  double rotation() const;
  void set_rotation(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid2d)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector2d* translation_;
  double rotation_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid2f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid2f) */ {
 public:
  Rigid2f();
  virtual ~Rigid2f();

  Rigid2f(const Rigid2f& from);

  inline Rigid2f& operator=(const Rigid2f& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Rigid2f(Rigid2f&& from) noexcept
    : Rigid2f() {
    *this = ::std::move(from);
  }

  inline Rigid2f& operator=(Rigid2f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid2f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid2f* internal_default_instance() {
    return reinterpret_cast<const Rigid2f*>(
               &_Rigid2f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(Rigid2f* other);
  friend void swap(Rigid2f& a, Rigid2f& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Rigid2f* New() const final {
    return CreateMaybeMessage<Rigid2f>(NULL);
  }

  Rigid2f* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Rigid2f>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Rigid2f& from);
  void MergeFrom(const Rigid2f& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid2f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Vector2f translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  private:
  const ::cartographer::transform::proto::Vector2f& _internal_translation() const;
  public:
  const ::cartographer::transform::proto::Vector2f& translation() const;
  ::cartographer::transform::proto::Vector2f* release_translation();
  ::cartographer::transform::proto::Vector2f* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector2f* translation);

  // float rotation = 2;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  float rotation() const;
  void set_rotation(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid2f)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector2f* translation_;
  float rotation_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid3d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid3d) */ {
 public:
  Rigid3d();
  virtual ~Rigid3d();

  Rigid3d(const Rigid3d& from);

  inline Rigid3d& operator=(const Rigid3d& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Rigid3d(Rigid3d&& from) noexcept
    : Rigid3d() {
    *this = ::std::move(from);
  }

  inline Rigid3d& operator=(Rigid3d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid3d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid3d* internal_default_instance() {
    return reinterpret_cast<const Rigid3d*>(
               &_Rigid3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(Rigid3d* other);
  friend void swap(Rigid3d& a, Rigid3d& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Rigid3d* New() const final {
    return CreateMaybeMessage<Rigid3d>(NULL);
  }

  Rigid3d* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Rigid3d>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Rigid3d& from);
  void MergeFrom(const Rigid3d& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid3d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Vector3d translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  private:
  const ::cartographer::transform::proto::Vector3d& _internal_translation() const;
  public:
  const ::cartographer::transform::proto::Vector3d& translation() const;
  ::cartographer::transform::proto::Vector3d* release_translation();
  ::cartographer::transform::proto::Vector3d* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector3d* translation);

  // .cartographer.transform.proto.Quaterniond rotation = 2;
  bool has_rotation() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  private:
  const ::cartographer::transform::proto::Quaterniond& _internal_rotation() const;
  public:
  const ::cartographer::transform::proto::Quaterniond& rotation() const;
  ::cartographer::transform::proto::Quaterniond* release_rotation();
  ::cartographer::transform::proto::Quaterniond* mutable_rotation();
  void set_allocated_rotation(::cartographer::transform::proto::Quaterniond* rotation);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid3d)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector3d* translation_;
  ::cartographer::transform::proto::Quaterniond* rotation_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid3f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid3f) */ {
 public:
  Rigid3f();
  virtual ~Rigid3f();

  Rigid3f(const Rigid3f& from);

  inline Rigid3f& operator=(const Rigid3f& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Rigid3f(Rigid3f&& from) noexcept
    : Rigid3f() {
    *this = ::std::move(from);
  }

  inline Rigid3f& operator=(Rigid3f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid3f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid3f* internal_default_instance() {
    return reinterpret_cast<const Rigid3f*>(
               &_Rigid3f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(Rigid3f* other);
  friend void swap(Rigid3f& a, Rigid3f& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Rigid3f* New() const final {
    return CreateMaybeMessage<Rigid3f>(NULL);
  }

  Rigid3f* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Rigid3f>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Rigid3f& from);
  void MergeFrom(const Rigid3f& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid3f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .cartographer.transform.proto.Vector3f translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  private:
  const ::cartographer::transform::proto::Vector3f& _internal_translation() const;
  public:
  const ::cartographer::transform::proto::Vector3f& translation() const;
  ::cartographer::transform::proto::Vector3f* release_translation();
  ::cartographer::transform::proto::Vector3f* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector3f* translation);

  // .cartographer.transform.proto.Quaternionf rotation = 2;
  bool has_rotation() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  private:
  const ::cartographer::transform::proto::Quaternionf& _internal_rotation() const;
  public:
  const ::cartographer::transform::proto::Quaternionf& rotation() const;
  ::cartographer::transform::proto::Quaternionf* release_rotation();
  ::cartographer::transform::proto::Quaternionf* mutable_rotation();
  void set_allocated_rotation(::cartographer::transform::proto::Quaternionf* rotation);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid3f)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector3f* translation_;
  ::cartographer::transform::proto::Quaternionf* rotation_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector2d

// double x = 1;
inline void Vector2d::clear_x() {
  x_ = 0;
}
inline double Vector2d::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2d.x)
  return x_;
}
inline void Vector2d::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2d.x)
}

// double y = 2;
inline void Vector2d::clear_y() {
  y_ = 0;
}
inline double Vector2d::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2d.y)
  return y_;
}
inline void Vector2d::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2d.y)
}

// -------------------------------------------------------------------

// Vector2f

// float x = 1;
inline void Vector2f::clear_x() {
  x_ = 0;
}
inline float Vector2f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2f.x)
  return x_;
}
inline void Vector2f::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2f.x)
}

// float y = 2;
inline void Vector2f::clear_y() {
  y_ = 0;
}
inline float Vector2f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2f.y)
  return y_;
}
inline void Vector2f::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2f.y)
}

// -------------------------------------------------------------------

// Vector3d

// double x = 1;
inline void Vector3d::clear_x() {
  x_ = 0;
}
inline double Vector3d::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.x)
  return x_;
}
inline void Vector3d::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.x)
}

// double y = 2;
inline void Vector3d::clear_y() {
  y_ = 0;
}
inline double Vector3d::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.y)
  return y_;
}
inline void Vector3d::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.y)
}

// double z = 3;
inline void Vector3d::clear_z() {
  z_ = 0;
}
inline double Vector3d::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.z)
  return z_;
}
inline void Vector3d::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.z)
}

// -------------------------------------------------------------------

// Vector3f

// float x = 1;
inline void Vector3f::clear_x() {
  x_ = 0;
}
inline float Vector3f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.x)
  return x_;
}
inline void Vector3f::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.x)
}

// float y = 2;
inline void Vector3f::clear_y() {
  y_ = 0;
}
inline float Vector3f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.y)
  return y_;
}
inline void Vector3f::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.y)
}

// float z = 3;
inline void Vector3f::clear_z() {
  z_ = 0;
}
inline float Vector3f::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.z)
  return z_;
}
inline void Vector3f::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.z)
}

// -------------------------------------------------------------------

// Vector4f

// float x = 1;
inline void Vector4f::clear_x() {
  x_ = 0;
}
inline float Vector4f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.x)
  return x_;
}
inline void Vector4f::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.x)
}

// float y = 2;
inline void Vector4f::clear_y() {
  y_ = 0;
}
inline float Vector4f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.y)
  return y_;
}
inline void Vector4f::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.y)
}

// float z = 3;
inline void Vector4f::clear_z() {
  z_ = 0;
}
inline float Vector4f::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.z)
  return z_;
}
inline void Vector4f::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.z)
}

// float t = 4;
inline void Vector4f::clear_t() {
  t_ = 0;
}
inline float Vector4f::t() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.t)
  return t_;
}
inline void Vector4f::set_t(float value) {
  
  t_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.t)
}

// -------------------------------------------------------------------

// Quaterniond

// double x = 1;
inline void Quaterniond::clear_x() {
  x_ = 0;
}
inline double Quaterniond::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.x)
  return x_;
}
inline void Quaterniond::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.x)
}

// double y = 2;
inline void Quaterniond::clear_y() {
  y_ = 0;
}
inline double Quaterniond::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.y)
  return y_;
}
inline void Quaterniond::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.y)
}

// double z = 3;
inline void Quaterniond::clear_z() {
  z_ = 0;
}
inline double Quaterniond::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.z)
  return z_;
}
inline void Quaterniond::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.z)
}

// double w = 4;
inline void Quaterniond::clear_w() {
  w_ = 0;
}
inline double Quaterniond::w() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.w)
  return w_;
}
inline void Quaterniond::set_w(double value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.w)
}

// -------------------------------------------------------------------

// Quaternionf

// float x = 1;
inline void Quaternionf::clear_x() {
  x_ = 0;
}
inline float Quaternionf::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.x)
  return x_;
}
inline void Quaternionf::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.x)
}

// float y = 2;
inline void Quaternionf::clear_y() {
  y_ = 0;
}
inline float Quaternionf::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.y)
  return y_;
}
inline void Quaternionf::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.y)
}

// float z = 3;
inline void Quaternionf::clear_z() {
  z_ = 0;
}
inline float Quaternionf::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.z)
  return z_;
}
inline void Quaternionf::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.z)
}

// float w = 4;
inline void Quaternionf::clear_w() {
  w_ = 0;
}
inline float Quaternionf::w() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.w)
  return w_;
}
inline void Quaternionf::set_w(float value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.w)
}

// -------------------------------------------------------------------

// Rigid2d

// .cartographer.transform.proto.Vector2d translation = 1;
inline bool Rigid2d::has_translation() const {
  return this != internal_default_instance() && translation_ != NULL;
}
inline void Rigid2d::clear_translation() {
  if (GetArenaNoVirtual() == NULL && translation_ != NULL) {
    delete translation_;
  }
  translation_ = NULL;
}
inline const ::cartographer::transform::proto::Vector2d& Rigid2d::_internal_translation() const {
  return *translation_;
}
inline const ::cartographer::transform::proto::Vector2d& Rigid2d::translation() const {
  const ::cartographer::transform::proto::Vector2d* p = translation_;
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2d.translation)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector2d*>(
      &::cartographer::transform::proto::_Vector2d_default_instance_);
}
inline ::cartographer::transform::proto::Vector2d* Rigid2d::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid2d.translation)
  
  ::cartographer::transform::proto::Vector2d* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Vector2d* Rigid2d::mutable_translation() {
  
  if (translation_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector2d>(GetArenaNoVirtual());
    translation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid2d.translation)
  return translation_;
}
inline void Rigid2d::set_allocated_translation(::cartographer::transform::proto::Vector2d* translation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete translation_;
  }
  if (translation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      translation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid2d.translation)
}

// double rotation = 2;
inline void Rigid2d::clear_rotation() {
  rotation_ = 0;
}
inline double Rigid2d::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2d.rotation)
  return rotation_;
}
inline void Rigid2d::set_rotation(double value) {
  
  rotation_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Rigid2d.rotation)
}

// -------------------------------------------------------------------

// Rigid2f

// .cartographer.transform.proto.Vector2f translation = 1;
inline bool Rigid2f::has_translation() const {
  return this != internal_default_instance() && translation_ != NULL;
}
inline void Rigid2f::clear_translation() {
  if (GetArenaNoVirtual() == NULL && translation_ != NULL) {
    delete translation_;
  }
  translation_ = NULL;
}
inline const ::cartographer::transform::proto::Vector2f& Rigid2f::_internal_translation() const {
  return *translation_;
}
inline const ::cartographer::transform::proto::Vector2f& Rigid2f::translation() const {
  const ::cartographer::transform::proto::Vector2f* p = translation_;
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2f.translation)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector2f*>(
      &::cartographer::transform::proto::_Vector2f_default_instance_);
}
inline ::cartographer::transform::proto::Vector2f* Rigid2f::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid2f.translation)
  
  ::cartographer::transform::proto::Vector2f* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Vector2f* Rigid2f::mutable_translation() {
  
  if (translation_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector2f>(GetArenaNoVirtual());
    translation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid2f.translation)
  return translation_;
}
inline void Rigid2f::set_allocated_translation(::cartographer::transform::proto::Vector2f* translation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete translation_;
  }
  if (translation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      translation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid2f.translation)
}

// float rotation = 2;
inline void Rigid2f::clear_rotation() {
  rotation_ = 0;
}
inline float Rigid2f::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2f.rotation)
  return rotation_;
}
inline void Rigid2f::set_rotation(float value) {
  
  rotation_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Rigid2f.rotation)
}

// -------------------------------------------------------------------

// Rigid3d

// .cartographer.transform.proto.Vector3d translation = 1;
inline bool Rigid3d::has_translation() const {
  return this != internal_default_instance() && translation_ != NULL;
}
inline void Rigid3d::clear_translation() {
  if (GetArenaNoVirtual() == NULL && translation_ != NULL) {
    delete translation_;
  }
  translation_ = NULL;
}
inline const ::cartographer::transform::proto::Vector3d& Rigid3d::_internal_translation() const {
  return *translation_;
}
inline const ::cartographer::transform::proto::Vector3d& Rigid3d::translation() const {
  const ::cartographer::transform::proto::Vector3d* p = translation_;
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3d.translation)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3d*>(
      &::cartographer::transform::proto::_Vector3d_default_instance_);
}
inline ::cartographer::transform::proto::Vector3d* Rigid3d::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3d.translation)
  
  ::cartographer::transform::proto::Vector3d* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Vector3d* Rigid3d::mutable_translation() {
  
  if (translation_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector3d>(GetArenaNoVirtual());
    translation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3d.translation)
  return translation_;
}
inline void Rigid3d::set_allocated_translation(::cartographer::transform::proto::Vector3d* translation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete translation_;
  }
  if (translation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      translation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3d.translation)
}

// .cartographer.transform.proto.Quaterniond rotation = 2;
inline bool Rigid3d::has_rotation() const {
  return this != internal_default_instance() && rotation_ != NULL;
}
inline void Rigid3d::clear_rotation() {
  if (GetArenaNoVirtual() == NULL && rotation_ != NULL) {
    delete rotation_;
  }
  rotation_ = NULL;
}
inline const ::cartographer::transform::proto::Quaterniond& Rigid3d::_internal_rotation() const {
  return *rotation_;
}
inline const ::cartographer::transform::proto::Quaterniond& Rigid3d::rotation() const {
  const ::cartographer::transform::proto::Quaterniond* p = rotation_;
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3d.rotation)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Quaterniond*>(
      &::cartographer::transform::proto::_Quaterniond_default_instance_);
}
inline ::cartographer::transform::proto::Quaterniond* Rigid3d::release_rotation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3d.rotation)
  
  ::cartographer::transform::proto::Quaterniond* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Quaterniond* Rigid3d::mutable_rotation() {
  
  if (rotation_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Quaterniond>(GetArenaNoVirtual());
    rotation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3d.rotation)
  return rotation_;
}
inline void Rigid3d::set_allocated_rotation(::cartographer::transform::proto::Quaterniond* rotation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete rotation_;
  }
  if (rotation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      rotation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, rotation, submessage_arena);
    }
    
  } else {
    
  }
  rotation_ = rotation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3d.rotation)
}

// -------------------------------------------------------------------

// Rigid3f

// .cartographer.transform.proto.Vector3f translation = 1;
inline bool Rigid3f::has_translation() const {
  return this != internal_default_instance() && translation_ != NULL;
}
inline void Rigid3f::clear_translation() {
  if (GetArenaNoVirtual() == NULL && translation_ != NULL) {
    delete translation_;
  }
  translation_ = NULL;
}
inline const ::cartographer::transform::proto::Vector3f& Rigid3f::_internal_translation() const {
  return *translation_;
}
inline const ::cartographer::transform::proto::Vector3f& Rigid3f::translation() const {
  const ::cartographer::transform::proto::Vector3f* p = translation_;
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3f.translation)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3f*>(
      &::cartographer::transform::proto::_Vector3f_default_instance_);
}
inline ::cartographer::transform::proto::Vector3f* Rigid3f::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3f.translation)
  
  ::cartographer::transform::proto::Vector3f* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Vector3f* Rigid3f::mutable_translation() {
  
  if (translation_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector3f>(GetArenaNoVirtual());
    translation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3f.translation)
  return translation_;
}
inline void Rigid3f::set_allocated_translation(::cartographer::transform::proto::Vector3f* translation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete translation_;
  }
  if (translation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      translation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3f.translation)
}

// .cartographer.transform.proto.Quaternionf rotation = 2;
inline bool Rigid3f::has_rotation() const {
  return this != internal_default_instance() && rotation_ != NULL;
}
inline void Rigid3f::clear_rotation() {
  if (GetArenaNoVirtual() == NULL && rotation_ != NULL) {
    delete rotation_;
  }
  rotation_ = NULL;
}
inline const ::cartographer::transform::proto::Quaternionf& Rigid3f::_internal_rotation() const {
  return *rotation_;
}
inline const ::cartographer::transform::proto::Quaternionf& Rigid3f::rotation() const {
  const ::cartographer::transform::proto::Quaternionf* p = rotation_;
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3f.rotation)
  return p != NULL ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Quaternionf*>(
      &::cartographer::transform::proto::_Quaternionf_default_instance_);
}
inline ::cartographer::transform::proto::Quaternionf* Rigid3f::release_rotation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3f.rotation)
  
  ::cartographer::transform::proto::Quaternionf* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline ::cartographer::transform::proto::Quaternionf* Rigid3f::mutable_rotation() {
  
  if (rotation_ == NULL) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Quaternionf>(GetArenaNoVirtual());
    rotation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3f.rotation)
  return rotation_;
}
inline void Rigid3f::set_allocated_rotation(::cartographer::transform::proto::Quaternionf* rotation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete rotation_;
  }
  if (rotation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      rotation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, rotation, submessage_arena);
    }
    
  } else {
    
  }
  rotation_ = rotation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3f.rotation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace transform
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftransform_2eproto
